### ISSUE TITLE
$.fn.saveAsXLS создает xls показываемую кракозябрами

### ISSUE THREAD

**Issue by jonny64** [do-/elu.js#1]
в сводном отчете можно выбрать 0 столбцов и 0 строк, тогда он состоит из одной строки Всего

`<html><body><table border><thead></thead><tbody><tr><th class="pvtTotalLabel pvtColTotalLabel" colspan="0">Всего</th><td class="pvtGrandTotal" data-value="9000">9 000</td></tr></tbody></table></body></html>
`
помогает UTF8 + BOM
```
('\uFEFF' + '<html><body><table border>' + this.html () + '</table></body></html>')
            .saveAs (name, 'application/vnd.ms-excel;charset=utf-8;')
```

Excel 2016
[test.zip](https://github.com/do-/elu.js/files/1779935/test.zip)

**Comment by do-** [comment]
Это правда помогает?

Скопировал строку выше к себе на тестовую. Перекомпилировал. Проверил: в _.js: и ufeff, и charset=utf-8 попали.

Однако байт в сгенерированных (Chrome 64.0.3282.186) файлах столько же и 1-й символ -- по-прежнему 3C ('<').

**Comment by do-** [comment]
Ага... Это я смотрел не тот проект — и там свой saveAsXLS (поскольку w2ui).

Так или иначе, commit 4f16b2ca6153e33c450c9d76a6ef33245b255632 должен исправить эту проблему (хотя немного иным способом, без BOM).
